"""
Email notification service.

Four modes, checked in priority order — no code changes needed to switch
between them, just environment variables:
  1. Resend   — if RESEND_API_KEY is set. Sends over HTTPS (port 443), so
                it works on Render's free tier, which blocks outbound
                SMTP ports (25/465/587) as of Sept 2025. Recommended for
                the deployed environment.
  2. SendGrid — if SENDGRID_API_KEY is set. Also HTTPS-based. Note:
                SendGrid's free plan was retired in 2025 (now a 60-day
                trial only).
  3. SMTP     — if SMTP_USERNAME and SMTP_PASSWORD are set (Gmail + an
                "app password", or any SMTP provider). Works locally;
                will NOT work on Render's free tier — SMTP ports are
                blocked there regardless of credentials.
  4. Console  — fallback if none of the above are configured; logs the
                email instead of sending it, so the POC is fully runnable
                with zero setup, locally or deployed.

v2: email body now includes the per-university explanation generated by
app/llm/explanation_service.py (LLM-written, or template fallback).
"""

import logging
import smtplib
from email.mime.text import MIMEText
from dataclasses import dataclass

import requests

from app.config.settings import (
    RESEND_API_KEY,
    SENDGRID_API_KEY,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USERNAME,
    SMTP_PASSWORD,
    NOTIFICATION_FROM_EMAIL,
)

logger = logging.getLogger("notifications")


@dataclass
class EmailResult:
    status: str  # "sent" | "console_logged" | "failed"
    detail: str = ""


def _build_recommendation_email_body(student_name: str, recommendation_items: list[dict]) -> str:
    lines = [f"Hi {student_name},", "", "Based on your profile, here are your top recommended programs:", ""]
    for i, item in enumerate(recommendation_items, start=1):
        lines.append(f"{i}. {item['university_name']} (match score: {item['score']})")
        explanation = item.get("explanation")
        if explanation:
            lines.append(f"   {explanation}")
        lines.append("")
    lines.append("Best regards,\nAdmissions Team")
    return "\n".join(lines)


def _send_via_resend(to_email: str, subject: str, body: str) -> EmailResult:
    try:
        response = requests.post(
            "https://api.resend.com/emails",
            headers={
                "Authorization": f"Bearer {RESEND_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "from": NOTIFICATION_FROM_EMAIL,
                "to": [to_email],
                "subject": subject,
                "text": body,
            },
            timeout=10,
        )
        if response.status_code in (200, 201):
            return EmailResult(status="sent", detail=f"Resend status {response.status_code}")
        return EmailResult(
            status="failed",
            detail=f"Resend status {response.status_code}: {response.text[:300]}",
        )
    except Exception as exc:  # noqa: BLE001 — POC-level: log and report failure, don't crash the request
        logger.exception("Failed to send recommendation email via Resend")
        return EmailResult(status="failed", detail=str(exc))


def _send_via_sendgrid(to_email: str, subject: str, body: str) -> EmailResult:
    try:
        import sendgrid
        from sendgrid.helpers.mail import Mail

        message = Mail(
            from_email=NOTIFICATION_FROM_EMAIL,
            to_emails=to_email,
            subject=subject,
            plain_text_content=body,
        )
        sg = sendgrid.SendGridAPIClient(SENDGRID_API_KEY)
        response = sg.send(message)
        if 200 <= response.status_code < 300:
            return EmailResult(status="sent", detail=f"SendGrid status {response.status_code}")
        return EmailResult(status="failed", detail=f"SendGrid status {response.status_code}")
    except Exception as exc:  # noqa: BLE001 — POC-level: log and report failure, don't crash the request
        logger.exception("Failed to send recommendation email via SendGrid")
        return EmailResult(status="failed", detail=str(exc))


def _send_via_smtp(to_email: str, subject: str, body: str) -> EmailResult:
    try:
        msg = MIMEText(body, "plain")
        msg["Subject"] = subject
        msg["From"] = NOTIFICATION_FROM_EMAIL
        msg["To"] = to_email

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(NOTIFICATION_FROM_EMAIL, [to_email], msg.as_string())

        return EmailResult(status="sent", detail=f"Sent via SMTP ({SMTP_HOST})")
    except smtplib.SMTPAuthenticationError as exc:
        logger.exception("SMTP authentication failed")
        return EmailResult(
            status="failed",
            detail=(
                "SMTP authentication failed. If using Gmail, make sure you're using an "
                "App Password (not your regular password) and that 2-Step Verification is "
                f"enabled on the account. Original error: {exc}"
            ),
        )
    except (TimeoutError, OSError) as exc:
        logger.exception("SMTP connection failed")
        return EmailResult(
            status="failed",
            detail=(
                "SMTP connection failed or timed out. If this is running on Render's free "
                "tier, note that outbound SMTP ports (25/465/587) are blocked there as of "
                f"Sept 2025 — use RESEND_API_KEY or SENDGRID_API_KEY instead. Original error: {exc}"
            ),
        )
    except Exception as exc:  # noqa: BLE001 — POC-level: log and report failure, don't crash the request
        logger.exception("Failed to send recommendation email via SMTP")
        return EmailResult(status="failed", detail=str(exc))


def send_recommendation_email(
    to_email: str, student_name: str, recommendation_items: list[dict]
) -> EmailResult:
    body = _build_recommendation_email_body(student_name, recommendation_items)
    subject = "Your University Recommendations"

    if RESEND_API_KEY:
        return _send_via_resend(to_email, subject, body)

    if SENDGRID_API_KEY:
        return _send_via_sendgrid(to_email, subject, body)

    if SMTP_USERNAME and SMTP_PASSWORD:
        return _send_via_smtp(to_email, subject, body)

    # Console fallback — POC runs without any external email account.
    logger.info(
        "[CONSOLE EMAIL] To: %s | From: %s | Subject: %s\n%s",
        to_email, NOTIFICATION_FROM_EMAIL, subject, body,
    )
    return EmailResult(
        status="console_logged",
        detail="No RESEND_API_KEY, SENDGRID_API_KEY, or SMTP_USERNAME/SMTP_PASSWORD set; logged instead of sent.",
    )
